app = "ton-nom-d-app" # Remplace par le nom de ton app sur Fly
primary_region = "cdg" # "cdg" pour Paris (Charles de Gaulle)

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[[statics]]
guest_path = "/var/www/html/public"
url_prefix = "/"

[deploy]
release_command = "php artisan migrate --force"

[env]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
